####################################################################################################
# Configuration file for smb-monitor (Windows app)
# This file is in the TOML format
# 
#! Must be set
#~ optional
####################################################################################################

#! Hostname of this server
SERVER_HOSTNAME = "HOSTNAME"

#! Path (including file name) to the file where to log the audits
LOG_FILE = ".\\samba-audit.log"

#~ default username to log activity
USER_NAME = "unknown.user"

#~ default user hostname to log activity
USER_HOSTNAME = "unknown-host"

#~ default user IP to log activity
USER_IP = "0.0.0.0"

#~ after what hour of day, in local time, should the audits log file be flushed (from 0 to 23)
PURGE_AFTER = 4

#! Shared folder(s) to be monitored on this server
[SHARES]
# SHARE_n = ["Name of Share", "Path\\to\\that\\share's\\folder"]
SHARE_1 = ["Shared Folder A", "C:\\SHARED\\shared_folder_A"]
SHARE_2 = ["Shared Folder B", "C:\\SHARED\\shared_folder_A"]
