####################################################################################################
# Configuration file for smb-monitor (Linux server)
# This file is in the TOML format
# 
#! Must be set
#~ optional
####################################################################################################

#~ Port to be used by the HTTP server:
# Default: 8080
#HTTP_PORT = 8080

#~ Path to log file (including file name):
# Default: "./smb-monitor.service.log"
#LOG_FILE = "./smb-monitor.service.log"

#~ Interval, in seconds, between checking audit file(s) for changes:
# Should be between 1 and 30 seconds [≥ 1, ≤ 30]
# 1 -> High CPU usage; Better refresh rate;
# 30 -> Low CPU usage; Worse refresh rate;
# Default: 5
#DELAY = 5

#! Email address to authenticate on the SMTP server and also used in the FROM field:
EMAIL_BOX = "email-box@domain.com, net, ..."

#! Password of the email to authenticate on the SMTP server:
EMAIL_PASSWORD = "your-smtp-password"

#! SMTP server:
SMTP = "your-smtp-server"

#! SMTP port:
SMTP_PORT = 587

#! Email address to send the alert to:
EMAIL_RECIPIENT = "email-box@domain.com, net, ..."

#~ Zabbix server IP:
# Default: None (in which case no reports at all will be sent to Zabbix)
#ZABBIX_SERVER_IP = "192.168.1.123"

#~ Zabbix server port:
# Default: 10051
#ZABBIX_SERVER_PORT = 10051

#~ The name of this host, in Zabbix:
# Default: None (in which case no general reports will be sent to Zabbix)
#ZABBIX_THIS_HOST = "HOSTNAME"

#~ Minimum number of unlink events to trigger an alert:
# Note: A threshold of 0 is invalid and will automatically fall back to the default value.
# minimum 1, maximum 65535
# Default: 50
#EXCESSIVE_UNLINKS_THRESHOLD = 99

#~ Time window, in seconds, to consider for the unlink events:
# minimum 1, maximum 65535
# Default: 300
#EXCESSIVE_UNLINKS_TIME_WINDOW = 300

#~ Cooldown, in seconds, to prevent multiple alerts:
# minimum 1, maximum 65535
# Default: 600
#EXCESSIVE_UNLINKS_COOLDOWN = 600

#~ Minimum number of move events to trigger an alert:
# Note: A threshold of 0 is invalid and will automatically fall back to the default value.
# minimum 1, maximum 65535
# Default: 50
#EXCESSIVE_MOVES_THRESHOLD = 99

#~ Time window, in seconds, to consider for the move events:
# minimum 1, maximum 65535
# Default: 300
#EXCESSIVE_MOVES_TIME_WINDOW = 300

#~ Cooldown, in seconds, to prevent multiple alerts:
# minimum 1, maximum 65535
# Default: 600
#EXCESSIVE_MOVES_COOLDOWN = 600

#! Audit file(s)
[AUDITS]
# AUDIT_n = ["Path/plus/filename/to/audit/file.log", "path/prefix/to/ignore/", "Time/Zone"]
#
# AUDIT_1
# AUDIT_2
# ...
# Audit_n
# (Start at 1! Don't skip numbers! AND don't repeat them!)
#
# Timezone cheat-sheet:
#	Castelo Branco: "Europe/Lisbon"
#	Ciudad Juárez: "America/Denver"
#	UTC: "Etc/UTC"
#
# /!\ These are examples!, Please fill in the correct data that fits your use case
#
# Example of a Linux Server set to UTC Timezone
# Its Samba Audit file is at /media/shared_disk_x/samba-audit.log
# Samba Audits log the complete file path, but it is very useful to ignore the first portion of it;
# In this example, we are going to ignore the prefix "/media/disk_name/SMB_Share_Root_Directory/";
# This avoids having duplicate and separate information for the same node (file or directory) if ever the SMB share root directory changes its path;
# In the event the SMB share root directory changes path, DO update that information here AND restart the service! Otherwise it would defeat its purpose.
# If you really don't want to ignore any portion of the path just fill in "" or "/" (This has not been extensively tested, because it is a bad idea)
AUDIT_1 = ["/media/shared_disk_x/samba-audit.log", "/media/disk_name/SMB_Share_Root_Directory/", "Etc/UTC"]
#
# Example of a Linux Server set to America/Denver Timezone
AUDIT_2 = ["/media/shared_disk_y/samba-audit.log", "/media/disk_name/SMB_Share_Root_Directory/", "America/Denver"]
#
# Example of a Windows machine set to Europe/Lisbon Timezone
# (I've also made a Windows app that monitors directory activity and writes a file in the same style as a Samba Audit)
# NOTE that the directory path separator is / and NOT \
AUDIT_3 = ["/media/shared_disk_z/samba-audit.log", "C:/DATA/", "Europe/Lisbon"]
#
# If you are only going to monitor a single SMB server, which could even be this same machine, you must at least have a correctly filled in AUDIT_1 array
